class EventSchema():
    @classmethod
    def get_dtypes(cls):
        return {
            "matchId": int,
            "id": float,
            "eventId": float,
            "minute": int,
            "second": float,
            "teamId": int,
            "playerId": float,
            "x": float,
            "y": float,
            "expandedMinute": int,
            "period": str,
            "type": str,
            "outcomeType": str,
            "isTouch": bool,
            "endX": float,
            "endY": float,
            "goalMouthZ": float,
            "goalMouthY": float,
            # "isShot": bool,
            "relatedEventId": float,
            "relatedPlayerId": float,
            # "isGoal": bool,
            "isOwnGoal": bool,
            "cardType": object,
            "blockedX": float,
            "blockedY": float,
            "playerName": str,
        }

    @classmethod
    def get_columns(cls):
        return [
            "matchId",
            "id",
            "eventId",
            "minute",
            "second",
            "teamId",
            "playerId",
            "x",
            "y",
            "expandedMinute",
            "period",
            "type",
            "outcomeType",
            "isTouch",
            "endX",
            "endY",
            "goalMouthZ",
            "goalMouthY",
            "relatedEventId",
            "relatedPlayerId",
            "isOwnGoal",
            "cardType",
            "blockedX",
            "blockedY",
            "playerName",
        ]
